### ISSUE TITLE
[raw-rdos] Extra notes appearing in some files

### ISSUE THREAD

**Issue by ildar** [Malvineous/libgamemusic#5]
> $ ./gamemus /tmp/"LAME intro tune for Xerox of INC.raw" -c dro-dosbox-v2:out.dro
> Opening /tmp/1.raw as type <autodetect>
> File is definitely: Rdos raw OPL capture [raw-rdos]
> decode-opl: Invalid OPL channel 15
> ...
> decode-opl: Invalid OPL channel 9
> Wrote out.dro as dro-dosbox-v2

When listening the resulting file it appears an extra note in the end of each phrase.

**Comment by Malvineous** [comment]
Can you supply the file that's doing this?

**Comment by ildar** [comment]
https://adplug.github.io/files/examples.zip

**Comment by Malvineous** [comment]
Thanks for that!  I can confirm I hear the extra notes when playing the file with `--play`, so the problem lies in the way the OPL data is being decoded.  I'll see if I can work out what's going on.

**Comment by Malvineous** [comment]
This one should be fixed now, thanks for reporting!
